# Generated by Django 4.1 on 2022-08-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
    ]
