# Generated by Django 4.1 on 2022-08-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=None, max_length=120, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.section', verbose_name='Section'),
        ),
    ]
