# Generated by Django 4.1 on 2022-08-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_task_name_alter_task_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.section', verbose_name='Section'),
        ),
    ]
