# Generated by Django 4.1 on 2022-08-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_task_name_alter_task_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
