# Generated by Django 4.1 on 2022-08-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_task_test_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test_price',
        ),
    ]
